### ISSUE TITLE
Should packages be org.osso.event?

### ISSUE THREAD

**Issue by matthew-dailey** [osso-project/osso#5]
Opening an issue since I wanted to make sure I had this right before opening a PR.
- Avro source files are under the namespace `com.osso.event`, but should that be `org.osso.event`?  The path to the files would also need to be changed to `.../org/osso/event`
- The pom also has groupId of `com.osso-project`, but should that be `org.osso-project`?

**Comment by esammer** [comment]
@matthew-dailey: You're right on both accounts. We should definitely make this change. Unfortunately, we can't make the packages `org.osso-project` because Java packages don't allow `-` characters. :(
